export const URL_API = "https://glbes.dokkaninfo.com/"
export const URL_SPRITE_SHEET = "https://dokkan.wiki/assets/global/en/outgame/effect/icon_rare_20000/en/icon_rare_20000-2.png"
export const URL_TYPE = "https://glbes.dokkaninfo.com/assets/global/es/layout/es/image/character/cha_type_icon_"
export const URL_RARITY = "https://glbes.dokkaninfo.com/assets/global/es/layout/es/image/character/cha_rare_sm_"
export const URL_EZA = "https://glbes.dokkaninfo.com/assets/global/es/layout/es/image/charamenu/dokkan/dok_img_" 